"""A self contained and systemd service enabled package for monitoring temperatures"""
__version__ = "0.2.1"

# These imports and constants are used by Loguru
from CONSTANTS import TIME_NOW
from pathlib import Path
from loguru import logger
RUNTIME_NAME = Path(__file__).name
RUNTIME_CWD = Path.cwd()
OS_FILENAME_SAFE_TIMESTR = "".join(i for i in TIME_NOW if i not in "\/:*?<>|")
import datetime as dt
import os


from humidity_and_temps_recorder import main
# This file is a wrapper around temperature monitor program.


@logger.catch
def defineLoggers(filename):
    class Rotator:
        """This code was generated by chatgpt as a suggestion for compression of rotated logs:
import datetime as dt
import gzip
import os

class Rotator:
    # Custom rotation handler that combines filesize limits with time controlled rotation.
    def __init__(self, *, size, at):
        now = dt.datetime.now()
        self._size_limit = size
        self._time_limit = now.replace(
            hour=at.hour, minute=at.minute, second=at.second
        )
        if now >= self._time_limit:
            # The current time is already past the target time so it would rotate already.
            # Add one day to prevent an immediate rotation.
            self._time_limit += dt.timedelta(days=1)

    def should_rotate(self, message, file):
        file.seek(0, 2)
        if file.tell() + len(message) > self._size_limit:
            return True
        if message.record["time"].timestamp() > self._time_limit.timestamp():
            self._time_limit += dt.timedelta(days=1)
            return True
        return False

    def rotate(self, path):
        # Rotate the file by renaming it with a timestamp.
        now = dt.datetime.now()
        backup_path = f"{path}.{now:%Y-%m-%d_%H-%M-%S}"
        os.rename(path, backup_path)
        # Compress the rotated file using gzip.
        with open(backup_path, "rb") as f_in:
            with gzip.open(f"{backup_path}.gz", "wb") as f_out:
                f_out.writelines(f_in)
        os.remove(backup_path)

# set rotate file if over 500 MB or at midnight every day
rotator = Rotator(size=5e8, at=dt.time(0, 0, 0))
# example usage: logger.add("file.log", rotation=rotator.should_rotate, rotation_message="Rotating log file")
"""
        # Custom rotation handler that combines filesize limits with time controlled rotation.
        def __init__(self, *, size, at):
            now = dt.datetime.now()
            self._size_limit = size
            self._time_limit = now.replace(
                hour=at.hour, minute=at.minute, second=at.second
            )
            if now >= self._time_limit:
                # The current time is already past the target time so it would rotate already.
                # Add one day to prevent an immediate rotation.
                self._time_limit += dt.timedelta(days=1)

        def should_rotate(self, message, file):
            file.seek(0, 2)
            if file.tell() + len(message) > self._size_limit:
                return True
            if message.record["time"].timestamp() > self._time_limit.timestamp():
                self._time_limit += dt.timedelta(days=1)
                return True
            return False

    # set rotate file if over 500 MB or at midnight every day
    rotator = Rotator(size=5e8, at=dt.time(0, 0, 0))
    # example useage: logger.add("file.log", rotation=rotator.should_rotate)

    # Begin logging definition
    logger.remove()  # removes the default console logger provided by Loguru.
    # I find it to be too noisy with details more appropriate for file logging.

    # INFO and messages of higher priority only shown on the console.
    # it uses the tqdm module .write method to allow tqdm to display correctly.
    # logger.add(lambda msg: tqdm.write(msg, end=""), format="{message}", level="ERROR")

    logger.configure(handlers=[{"sink": os.sys.stderr, "level": "INFO"}])
    # this method automatically suppresses the default handler to modify the message level

    logger.add(
        "".join(["./LOGS/", filename, "_{time}.log"]),
        rotation="12:00",
        level="DEBUG",
        encoding="utf8",
        compression="zip",
    )
    # create a new log file for each run of the program
    #
    # TODO set a compression rule for older log files
    return


defineLoggers(f"{RUNTIME_NAME}_{OS_FILENAME_SAFE_TIMESTR}")
logger.info("Program Start.")  # log the start of the program
main()
logger.info("Program End.")
