[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EntroPi"
authors = [{name = "Conrad Storz", email = "conradstorz@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/conradstorz/Home_HVAC.git"
